adding grpc port and env
fluidshare/helm-charts pull request #32
Opened 2021-02-10 23:12 UTC by tofluid

Adding grpc support to service.yaml and deployment.yaml
Adding env support for deployment.yaml container

2021-02-10 23:15 UTC, ellisio requested changes

2021-02-10 23:15 UTC, ellisio commented on charts/golang/templates/deployment.yaml
> +            value: {{ .value }}
This isn't needed. We do this here:

https://github.com/fluidshare/helm-charts/blob/main/charts/golang/templates/deployment.yaml#L87-L89

2021-02-10 23:18 UTC, tofluid commented on charts/golang/templates/deployment.yaml
> +            value: {{ .value }}
removed

2021-02-23 16:32 UTC, ellisio requested changes

2021-02-23 16:32 UTC, ellisio commented on charts/golang/templates/service.yaml
> +      nodePort: {{ .Values.service.grpc.nodePort  }}
@tofluid Couple things here:

1. It looks like you're missing the `service.grpc` block within `values.yaml` to provide a default configuration, with documentation on what that block is for.
2. The last condition on line 40 needs to be `empty .Values.service.grpc.nodePort`.

2021-02-23 16:34 UTC, ellisio requested changes

2021-02-23 16:34 UTC, ellisio commented on charts/golang/templates/deployment.yaml
> +            {{- end }}
This block seems a little confusing. If GRPC is enabled, you're looking for a root value. Can this be refactored to look for `.Values.service.grpc.port`? That way you can put a default value in the `service.grpc` config along with the `nodePort`.

2021-02-23 16:36 UTC, tofluid commented on charts/golang/templates/deployment.yaml
> +            {{- end }}
i had done that originally then decided that i wanted to try to match how http was done. I'll revert

2021-02-23 16:41 UTC, tofluid commented on charts/golang/templates/service.yaml
> +      nodePort: {{ .Values.service.grpc.nodePort  }}
1. Added to values.yaml
2. changed

2021-02-23 16:56 UTC, ellisio requested changes

2021-02-23 16:56 UTC, ellisio commented on charts/golang/templates/deployment.yaml
> +            {{- if .Values.service.grpc }}
Lets do a check here for `.Values.service.grpc.port`.

2021-02-23 16:56 UTC, ellisio commented on charts/golang/templates/deployment.yaml
> +              value: {{ quote .Values.service.grpc.applicationPort }}
Reference `.Values.service.grpc.port` instead.

2021-02-23 16:56 UTC, ellisio commented on charts/golang/templates/deployment.yaml
> +          {{- if .Values.service.grpc }}
Lets do a check here for `.Values.service.grpc.port`.

2021-02-23 16:56 UTC, ellisio commented on charts/golang/templates/deployment.yaml
> +              containerPort: {{ .Values.service.grpc.applicationPort }}
Reference `.Values.service.grpc.port` instead.

2021-02-23 16:56 UTC, ellisio commented on charts/golang/templates/service.yaml
> +    {{- if .Values.service.grpc }}
Lets do a check here for `.Values.service.grpc.port`.

2021-02-23 16:56 UTC, ellisio commented on charts/golang/values.yaml
> +
If you're using an editor that supports EditorConfig, make sure you have that plugin installed. I think you can do this in any IntelliJ IDE.

2021-02-23 16:56 UTC, ellisio commented on charts/golang/values.yaml
> +  # grpc:
Leave this line uncommented.

2021-02-23 16:56 UTC, ellisio commented on charts/golang/values.yaml
> +    # applicationPort: 8090
You can remove this comment and line.

2021-02-23 17:08 UTC, tofluid commented on charts/golang/templates/deployment.yaml
> +            {{- if .Values.service.grpc }}
in this case i'll check for `applicationPort` as that's what's used in this block

2021-02-23 17:12 UTC, tofluid commented on charts/golang/values.yaml
> +  # grpc:
done

2021-02-23 17:40 UTC, tofluid commented on charts/golang/templates/deployment.yaml
> +              value: {{ quote .Values.service.grpc.applicationPort }}
done

2021-02-23 17:40 UTC, tofluid commented on charts/golang/templates/deployment.yaml
> +          {{- if .Values.service.grpc }}
done

2021-02-23 17:40 UTC, tofluid commented on charts/golang/templates/service.yaml
> +    {{- if .Values.service.grpc }}
done

2021-02-23 17:40 UTC, tofluid commented on charts/golang/values.yaml
> +
done

2021-02-23 17:41 UTC, tofluid commented on charts/golang/values.yaml
> +    # applicationPort: 8090
done

2021-02-23 18:00 UTC, ellisio approved these changes

2021-02-23 18:01 UTC, merged